LEXICON = {
    "uz": {
        "select_lang": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык:",
        "welcome_reg": "Xush kelibsiz! Ro'yxatdan o'tishni boshlash uchun ismingizni kiriting:",
        "req_lastname": "Familiyangizni kiriting:",
        "req_phone": "Telefon raqamingizni yuboring (Tugma orqali):",
        "main_menu": "Asosiy menyu:",
        "btn_catalog": "📚 Katalog",
        "btn_my_lib": "📖 Mening kutubxonam",
        "btn_balance": "💳 Balans",
        "btn_profile": "👤 Profil",
        "btn_search": "🔍 Qidirish",
        "btn_settings": "⚙️ Sozlamalar",
        "btn_send_phone": "📱 Telefon raqamni yuborish",
        "insufficient_funds": "Balansingizda mablag' yetarli emas.",
        "purchase_success": "Kitob muvaffaqiyatli xarid qilindi!",
        "buy": "Sotib olish",
        "read": "O'qish (PDF)",
        "listen": "Audioda tinglash",
        "fill_balance": "💰 Balansni to'ldirish",
        "req_amount": "To'ldirmoqchi bo'lgan summani kiriting (UZS): plastik raqam
        8800902249968571 ",
        "req_check": "To'lov chekini (rasm shaklida) yuboring:",
        "check_sent_admin": "Chek adminga yuborildi.",
        "no_books": "Hozircha kitoblar mavjud emas."
    },
    "ru": {
        "select_lang": "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык:",
        "welcome_reg": "Добро пожаловать! Введите ваше имя:",
        "req_lastname": "Введите вашу фамилию:",
        "req_phone": "Отправьте ваш номер телефона (через кнопку):",
        "main_menu": "Главное меню:",
        "btn_catalog": "📚 Каталог",
        "btn_my_lib": "📖 Моя библиотека",
        "btn_balance": "💳 Баланс",
        "btn_profile": "👤 Профиль",
        "btn_search": "🔍 Поиск",
        "btn_settings": "⚙️ Настройки",
        "btn_send_phone": "📱 Отправить номер телефона",
        "insufficient_funds": "Недостаточно средств на балансе.",
        "purchase_success": "Книга успешно приобретена!",
        "buy": "Купить",
        "read": "Читать (PDF)",
        "listen": "Слушать аудио",
        "fill_balance": "💰 Пополнить баланс",
        "req_amount": "Введите сумму пополнения (UZS):",
        "req_check": "Отправьте чек оплаты (в виде фото):",
        "check_sent_admin": "Чек отправлен админу.",
        "no_books": "Книг пока нет."
    }
}
